# Generated by Django 6.0 on 2026-08-23 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code_prefix', models.CharField(max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('supplier_type', models.CharField(choices=[('food', 'Food & Ingredients'), ('equipment', 'Equipment & Tools'), ('packaging', 'Packaging'), ('services', 'Services'), ('other', 'Other')], default='food', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('par_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('price_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('storage_conditions', models.CharField(blank=True, max_length=200)),
                ('is_secret', models.BooleanField(default=False)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_status', models.CharField(blank=True, choices=[('testing', 'Under Testing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='testing', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, choices=[('taste', 'Taste'), ('price', 'Price'), ('other', 'Other')], max_length=20)),
                ('rejection_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='ingredients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternatives', models.ManyToManyField(blank=True, related_name='alternative_for', to='lab.ingredient')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='lab.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='lab.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('recorded_at', models.DateField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='lab.ingredient')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MealTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=120)),
                ('success_rate', models.PositiveSmallIntegerField(default=0)),
                ('taste', models.PositiveSmallIntegerField(default=0)),
                ('texture', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('consistency', models.PositiveSmallIntegerField(default=0)),
                ('overall', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('suitable', 'Suitable'), ('not_suitable', 'Not Suitable'), ('emergency_substitute', 'Emergency Substitute')], default='suitable', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cooking_temperature', models.PositiveIntegerField(blank=True, null=True)),
                ('cooking_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('repetition_number', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='trials/')),
                ('final_dish_photo', models.ImageField(blank=True, upload_to='trials/dishes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='trials', to='lab.ingredient')),
                ('parent_trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='lab.mealtrial')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='lab.supplier')),
            ],
            options={
                'ordering': ['-trial_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=120)),
                ('taste', models.PositiveSmallIntegerField(default=0)),
                ('texture', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('consistency', models.PositiveSmallIntegerField(default=0)),
                ('overall', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_ratings', to='lab.mealtrial')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_steps', to='lab.mealtrial')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('avg_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('recommendation', models.CharField(choices=[('approved', 'Approved'), ('backup_only', 'Backup Only'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='evaluations', to='lab.ingredient')),
                ('trials', models.ManyToManyField(blank=True, related_name='evaluations', to='lab.mealtrial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(default='g', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_uses', to='lab.ingredient')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='lab.mealtrial')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('qa', 'QA'), ('procurement', 'Procurement')], default='chef', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
