# Generated by Django 6.0 on 2026-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtrial',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealtrial',
            name='expiry_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealtrial',
            name='expiry_unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10),
        ),
    ]
