# Generated by Django 6.0 on 2026-09-15 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remap_roles(apps, schema_editor):
    UserProfile = apps.get_model("lab", "UserProfile")
    mapping = {
        "chef": "staff",
        "qa": "staff",
        "procurement": "viewer",
    }
    for old, new in mapping.items():
        UserProfile.objects.filter(role=old).update(role=new)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_mealtrial_pending_verdict_rejection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("viewer", "Viewer"),
                    ("it", "IT"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.RunPython(remap_roles, noop_reverse),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(blank=True, max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
